name: Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # jobs
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:app"
          push: true
          tags: gk13081987/lastrepo:${{ github.sha }}
    
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'lastwebapp'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          images: 'gk13081987/lastrepo:${{ github.sha }}'
